project:
  type: book
  output-dir: docs

book:
  title: "Designing Webpages"
  author: "Alistair Bailey"
  date: last-modified
  date-format: "[Last Updated on] YYYY-MM-DD"
  #cover-image: cover.png
  reader-mode: true  
  page-footer:
      left: |
        This font is <a href="https://brailleinstitute.org/freefont">Atkinson Hyperlegible</a>.
      right: |
        This book was built with <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - what-to-read-instead.qmd
    - how-people-access-webpages.qmd
    - how-people-read-webpages.qmd
    - how-to-write-for-the-web.qmd
    - how-to-use-imagery-and-visuals.qmd
    - references.qmd
  
bibliography: references.bib

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    theme:
      light: [cosmo, styles.scss]
      dark: [dark.scss]
  
  #pdf:
    #documentclass: scrreprt

editor: visual

