---
bibliography: references.bib
---

# How to write for the web {#sec-how-to-write-for-the-web}

::: {.callout-important .unnumbered title="Summary" appearance="simple" icon="false"}
Good writing is easy to read and understand. It uses short sentences, simple vocabulary and is broken into chunks.
:::

@sec-how-do-people-read-webpages discussed the observations that:

-   Users scan rather than read (@sec-people-scan-webpages).

-   Users have finite cognitive capacity (@sec-working-memory).

And how page structure can make scanning easier and information easier to retain.

However, we can also address these issues through our writing, primarily by:

-   Removing or reducing our use of jargon or complex language.

-   Being more concise.

NN/g also have a page collating articles and videos specifically related to writing for the web based on their research: [NN/g UX Writing: Study Guide](https://www.nngroup.com/articles/ux-writing-study-guide/)

## How to write better sentences {#sec-how-to-write-better-sentences}

My favourite resource for improving writing is a short paper by Jonathan Bennett and Samuel Gorovitz in which they describe 'Bennett Rules' for sentences [@bennett1997].

I've extracted the Bennett Rules here, but I encourage you to read the whole thing as it provides greater context and explanation.

A key point is that comparison is often the best way to understand whether we can improve a sentence.

1.  Verbs are better than nouns. Compare:

    > There is a difference between waving and drowning.

    > Waving differs from drowning.

2.  Adverbs are better than adjectives. Compare:

    > She is a clear writer.

    > She writes clearly.

3.  Favour the Anglo-Saxon. Compare:

    > Is it possible for him to...? (*possible* has Latin roots)

    > Can he...? (*can* has Anglo-Saxon roots)

4.  Banish 'very' and its ilk. Compare:

    > It's very unlikely.

    > It's unlikely.

5.  Abstract nouns should be fought like the devil. Compare:

    > Our exploration of the formulations' implications for readability reveals that each are unacceptable.

    > We explore what each formulation implies for readability and find that none are acceptable.

6.  Avoid undue repetition.

7.  Be careful with commas. I'd extend this rule to suggest that breaking long sentences into smaller ones is generally good advice. Sentences full of commas, semi-colons and colons are potentially more confusing and harder to read.

8.  Attend to the sound. Test your writing by reading it aloud.

As discussed in @sec-the-unconsidered-webpage-is-not-worth-creating , the purpose of these rules is to provide practical guidance when creating your content. You may decide a more verbose or Latin rooted construction works best. The aim is to help you think about how to write sentences that the user will find easy to read and understand.

## Make link text informative {#sec-make-link-text-informative}

When linking, rather than "here", "more" or "go", use descriptive text or the page title as the link such as this link to [Wikipedia's photo of a domestic rabbit stretched out on a carpet](https://en.wikipedia.org/wiki/Domestic_rabbit#/media/File:Domestic_Rabbit_Relaxed_on_Carpet.jpg).

Links with descriptive text are helpful for anyone using a screen reader and for all users in understanding what a link leads to.

## Editing your own words {#sec-editing-your-own-words}

It is difficult to edit ones own words. Over-familiarity leads to word-blindness and an inability to spot typos. And it is difficult to step outside of oneself and consider how our words come across to someone else.

Ideally one would have an editor available to review and copy-edit our words, but this isn't always possible. If you are unable to recruit a trusted colleague to review your writing, Hannah Boursnell has written a two part blog with advice on how to edit your own work: [10 editing hacks - Part 1](https://www.hannahboursnell.com/blog/10editinghacks) and [10 editing hacks - Part 2](https://www.hannahboursnell.com/blog/10editinghacks2).
