# [Cheeky boar leaves nudist grunting in laptop chase]{style="font-family:'EB Garamond'"}<br>
[**A nudist in Berlin got too close to nature for comfort when a wild boar snatched his plastic bag - which had his laptop inside.**
<br>
The naked man gave chase to the boar and her two piglets - much to the amusement of fellow sunbathers.
<br>
Adele Landauer, an actor and life coach, took photos of the chase at Teufelssee - a popular bathing spot - and put them on Facebook.
<br>
"Nature strikes back!" she wrote, adding that the man laughed it all off.
<br>
"He gave it his all", with not a stitch on, she reported. "I then showed the photos to the man, he laughed soundly and authorised me to make them public."]{style="font-family:'EB Garamond'"}

[PDF Font: EB Garamond]{style="font-family:'EB Garamond'"}

# [Cheeky boar leaves nudist grunting in laptop chase]{style="font-family:'Libre Franklin'"}<br>
[**A nudist in Berlin got too close to nature for comfort when a wild boar snatched his plastic bag - which had his laptop inside.**
<br>
The naked man gave chase to the boar and her two piglets - much to the amusement of fellow sunbathers.
<br>
Adele Landauer, an actor and life coach, took photos of the chase at Teufelssee - a popular bathing spot - and put them on Facebook.
<br>
"Nature strikes back!" she wrote, adding that the man laughed it all off.
<br>
"He gave it his all", with not a stitch on, she reported. "I then showed the photos to the man, he laughed soundly and authorised me to make them public."]{style="font-family:'Libre Franklin'"}

[Newsprint Font: Libre Franklin]{style="font-family:'Libre Franklin'"}

# [Cheeky boar leaves nudist grunting in laptop chase]{style="font-family:'Roboto'"}<br>
[**A nudist in Berlin got too close to nature for comfort when a wild boar snatched his plastic bag - which had his laptop inside.**
<br>
The naked man gave chase to the boar and her two piglets - much to the amusement of fellow sunbathers.
<br>
Adele Landauer, an actor and life coach, took photos of the chase at Teufelssee - a popular bathing spot - and put them on Facebook.
<br>
"Nature strikes back!" she wrote, adding that the man laughed it all off.
<br>
"He gave it his all", with not a stitch on, she reported. "I then showed the photos to the man, he laughed soundly and authorised me to make them public."]{style="font-family:'Roboto'"}

[Web Font: Roboto]{style="font-family:'Roboto'"}

# Cheeky boar leaves nudist grunting in laptop chase

**A nudist in Berlin got too close to nature for comfort when a wild boar snatched his plastic bag - which had his laptop inside.**

The naked man gave chase to the boar and her two piglets - much to the amusement of fellow sunbathers.

Adele Landauer, an actor and life coach, took photos of the chase at Teufelssee - a popular bathing spot - and put them on Facebook.

"Nature strikes back!" she wrote, adding that the man laughed it all off.

"He gave it his all", with not a stitch on, she reported. "I then showed the photos to the man, he laughed soundly and authorised me to make them public."

Readability Font: Noto Sans

[BBC original page](https://www.bbc.co.uk/news/world-europe-53692475)
